### ISSUE TITLE
[MVP4]職員用検索結果画面

### ISSUE THREAD

**Issue by onsd** [NITTC-ComputerClub/SeiDoc#103]
![image](https://user-images.githubusercontent.com/29172177/63857904-7b000680-c9df-11e9-964c-760f9e09104d.png)

**Comment by onsd** [comment]
これ、firebaseからfetchするように変更したので世代もとってこれるようになったんですけど、どうします？

**Comment by asasigure1209** [comment]
表示したい

**Comment by onsd** [comment]
`system.monthlyView` みたいにsystem型の中に入ってるのでCSSあてるついでに頼める？

**Comment by asasigure1209** [comment]
了解

**Comment by onsd** [comment]
それができたらこれもcloseかな

**Comment by asasigure1209** [comment]
@onsd 
![image](https://user-images.githubusercontent.com/31458031/65811461-866b6b00-e1f3-11e9-8e1f-9ee26a94ae89.png)
閲覧されていないのに人気の世代出るのはなぜ？

**Comment by onsd** [comment]
どの制度？

**Comment by asasigure1209** [comment]
ひとり親家庭手当・愛知県遺児手当

**Comment by onsd** [comment]
なんでこれ二つあるんだろ

データにはageGroup存在しますね...
見たときの処理がうまくいってない？

**Comment by onsd** [comment]
algoliaSearchに二つデータが入ってたから一個は消した

**Comment by onsd** [comment]
Adminが見たときは閲覧数を増やさないようにしてるんだけど、年代の集計のところでAdminを弾いてなかったからっぽい

直します

**Comment by onsd** [comment]
#260 これでなおるといいけど

今日の分は間に合ってないので閲覧数が0, ageGroupになんか入ってる制度は明日まで生まれてしまうのでageGroupだけ消さないといけない
