### ISSUE TITLE
カテゴリ別の制度閲覧状況から各々のランキングに飛ぶ

### ISSUE THREAD

**Issue by watamoko** [NITTC-ComputerClub/SeiDoc#162]
![image](https://user-images.githubusercontent.com/46018454/64675753-e56c7880-d4ae-11e9-9ff0-14348980b8ea.png)

Topのここからランキングページに飛びます

**Comment by onsd** [comment]
これ完成してそう、


できてたらClose してくださーい
@watamoko

**Comment by watamoko** [comment]
ランキングページ作ったついでにできてしまってた
