### ISSUE TITLE
ランキング画面のデザイン作成

### ISSUE THREAD

**Issue by watamoko** [NITTC-ComputerClub/SeiDoc#178]
![image](https://user-images.githubusercontent.com/46018454/64906329-3d5de600-d720-11e9-8765-17ea759f4555.png)

・いまの/admin/status画面ではプルダウンでカテゴリ変更されるのでそれをタブ形式に変えます
・決め打ちになってるのでちゃんとランキングにします
・/admin/の「さらに詳しく」から左のページに飛ぶように変えます

**Comment by watamoko** [comment]
@asasigure1209 CSSお願いします

**Comment by watamoko** [comment]
/admin/categoryRanking
/admin/totalRanking
の2画面です

**Comment by asasigure1209** [comment]
前のPRでやってますね
