### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by onsd** [NITTC-ComputerClub/SeiDoc#182]
`https://sei-doc.web.app/aaaaaa`

ちょっとほしい

**Comment by onsd** [comment]
これ、出す言葉とか書いておいてくれればページはつくりますが

**Comment by onsd** [comment]
あったわ

**Comment by onsd** [comment]
`        <Route compnent={NotFound} /> ` 
これ。react-router v4 でつかえないんすかね

**Comment by sasa-kou** [comment]
つかえると思うけど
できなかった？

**Comment by onsd** [comment]
できました....

**Comment by sasa-kou** [comment]
よかった
