### ISSUE TITLE
CSV出力の配列表現がおかしい

### ISSUE THREAD

**Issue by sasa-kou** [NITTC-ComputerClub/SeiDoc#230]

**Comment by onsd** [comment]
これ、正解がわからないから教えてほしい
```javascript
[
{"name": "子ども支援" , "category" : ["A","B"],
{"name":大人支援", "category": ["A"] }
]
```
こういうデータが有ったときに、

|name|category|category|
|----|----|----|
|子ども支援|A|B|
|大人支援|A| | 

こんな感じのCSV出てきても困るしなぁというお気持ち

**Comment by onsd** [comment]
一つの解答的には、上記の例を使うと

|name|category|
|----|----|
|子ども支援|A|
|子ども支援|B|
|大人支援|A|

ってやるとかかな

**Comment by watamoko** [comment]
https://www.e-stat.go.jp/statistics-by-theme/
ここからいろいろ見ていく感じだと"、"で区切られてるものが多かった
手入力だとまぁそうだよねって感じ

| name | category |
| :---: | :---: |
| 子ども支援 | A、B |
| 大人支援 | A |

になるかと

**Comment by watamoko** [comment]
https://www.data.go.jp/data/dataset?res_format=CSV&q=&sort=extras_release_date+desc-20
やっぱ"、"区切りだわ
てか改めて思ったけどまともなデータが少ない
