### ISSUE TITLE
地域から調べる

### ISSUE THREAD

**Issue by sasa-kou** [NITTC-ComputerClub/SeiDoc#252]

**Comment by sasa-kou** [comment]
<img width="177" alt="スクリーンショット 2019-09-27 12 49 19" src="https://user-images.githubusercontent.com/26497142/65740897-4342c680-e125-11e9-91ea-47d4501e0dae.png">
このページを/region

<img width="172" alt="スクリーンショット 2019-09-27 12 50 21" src="https://user-images.githubusercontent.com/26497142/65740933-62415880-e125-11e9-9297-0da112d9e0e4.png">
ここは/categoryをそのまま

<img width="173" alt="スクリーンショット 2019-09-27 12 50 59" src="https://user-images.githubusercontent.com/26497142/65740955-7ab17300-e125-11e9-95ea-01ac35959704.png">
ここを/search?tag=子育て&region=愛知県名古屋市

で考えてるんですけどどうですか
@asasigure1209 @onsd

**Comment by asasigure1209** [comment]
僕は問題なし

**Comment by onsd** [comment]
(๑•̀ㅂ•́)و✧

**Comment by onsd** [comment]
これ、adminのときはどういう仕様になる？

**Comment by onsd** [comment]
#262 
検索は作ったので画面遷移のやつよろしくです
