### ISSUE TITLE
login,signup時のバリデーション

### ISSUE THREAD

**Issue by sasa-kou** [NITTC-ComputerClub/SeiDoc#274]

**Comment by onsd** [comment]
ついでに
+ enter押して確定できるやつ

**Comment by watamoko** [comment]
enter押して確定できるやつって居住区の入力後にエンター押したらって感じですか

![image](https://user-images.githubusercontent.com/46018454/66482187-64b89080-eadd-11e9-8c36-8d25745e9cf4.png)

**Comment by onsd** [comment]
新規登録のとこのenter押して確定はいらん気がする
暴発しそう

**Comment by watamoko** [comment]
りょ
